## import Packages

In [1]:
import pandas as pd
import numpy as np

### upload the data

In [2]:
df = pd.read_csv('dirty_cafe_sales.csv')

### Explore the data

In [3]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [4]:
df.sample(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
3326,TXN_4476151,Juice,4,3.0,12.0,Credit Card,In-store,2023-02-15
5243,TXN_9563024,Cookie,3,ERROR,3.0,Digital Wallet,In-store,2023-09-27
7194,TXN_3896128,Cake,1,3.0,UNKNOWN,NaN,In-store,2023-01-04
6985,TXN_6347482,Tea,2,1.5,3.0,Digital Wallet,NaN,2023-07-10
9559,TXN_1937081,Cake,2,3.0,6.0,Credit Card,NaN,2023-06-07
7516,TXN_6787259,Sandwich,2,4.0,8.0,Credit Card,In-store,2023-08-18
3463,TXN_3174488,UNKNOWN,4,1.0,4.0,Cash,Takeaway,2023-06-28
1399,TXN_5856820,Tea,2,1.5,3.0,Credit Card,Takeaway,2023-07-18
9641,TXN_1661682,ERROR,5,4.0,20.0,Digital Wallet,NaN,2023-07-13
4550,TXN_3384640,Salad,4,5.0,20.0,NaN,Takeaway,2023-10-17

In [5]:
df.columns

Index(['Transaction ID', 'Item', 'Quantity', 'Price Per Unit', 'Total Spent',
       'Payment Method', 'Location', 'Transaction Date'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [7]:
df.describe()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_9226047,Juice,5,3.0,6.0,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

In [8]:
print(df['Item'].value_counts())
print(20 * '#')
print(df['Quantity'].value_counts())
print(20 * '#')

Item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
UNKNOWN      344
ERROR        292
Name: count, dtype: int64
####################
Quantity
5          2013
2          1974
4          1863
3          1849
1          1822
UNKNOWN     171
ERROR       170
Name: count, dtype: int64
####################

In [9]:
print(df['Payment Method'].value_counts())
print(20 * '#')
print(df['Location'].value_counts())

Payment Method
Digital Wallet    2291
Credit Card       2273
Cash              2258
ERROR              306
UNKNOWN            293
Name: count, dtype: int64
####################
Location
Takeaway    3022
In-store    3017
ERROR        358
UNKNOWN      338
Name: count, dtype: int64

` It is clear that we we need to fill the UNKOWN and ERROR values with the appropriate value  `

In [10]:
df.isna().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

` We have many NaNs values `

### We will check if there is any duplicate

In [11]:
df.duplicated().sum()

np.int64(0)

### We need to convert the UNKNOWN and ERROR values to NaN to treat them the same

In [64]:
df.replace(["UNKNOWN", "ERROR"], np.nan, inplace=True)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,NaN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [65]:
df[['Item', 'Price Per Unit']].value_counts()

Item      Price Per Unit
Juice     3.0               1110
Coffee    2.0               1108
Cake      3.0               1085
Salad     5.0               1082
Sandwich  4.0               1082
Smoothie  4.0               1036
Cookie    1.0               1026
Tea       1.5               1023
Name: count, dtype: int64

In [66]:
df['Item'].isna().sum()

np.int64(969)

In [67]:
df[df['Price Per Unit'].isna()]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
56,TXN_3578141,Cake,5,NaN,15.0,NaN,Takeaway,2023-06-27
65,TXN_4987129,Sandwich,3,NaN,NaN,NaN,In-store,2023-10-20
68,TXN_8427104,Salad,2,NaN,10.0,NaN,In-store,2023-10-27
85,TXN_8035512,Tea,3,NaN,4.5,Cash,NaN,2023-10-29
104,TXN_7447872,Juice,2,NaN,6.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
9924,TXN_5981429,Juice,2,NaN,6.0,Digital Wallet,NaN,2023-12-24
9926,TXN_2464706,Cake,4,NaN,12.0,Digital Wallet,Takeaway,2023-11-09
9961,TXN_2153100,Tea,2,NaN,3.0,Cash,NaN,2023-12-29
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02

### Fill Price based on most frequent Price within same Item

In [68]:
df["Price Per Unit"] = df["Price Per Unit"].fillna(
    df.groupby("Item")["Price Per Unit"]
      .transform(lambda x: x.mode()[0] if not x.mode().empty else np.nan)
)

### Fill Items based on most frequent item within same Price

In [69]:
df["Item"] = df["Item"].fillna(
    df.groupby("Price Per Unit")["Item"]
      .transform(lambda x: x.mode()[0] if not x.mode().empty else np.nan)
)

In [70]:
print(df['Item'].isna().sum())
print(df['Price Per Unit'].isna().sum())

54
54

` We can Note that we still have NaNs in Item and Price  We will handle it later`

In [71]:
df['Payment Method'].value_counts()

Payment Method
Digital Wallet    2291
Credit Card       2273
Cash              2258
Name: count, dtype: int64

### Converting Types

In [117]:
df['Item'] = df['Item'].astype('category')
df['Quantity'] = df['Quantity'].astype('float32')
df['Price Per Unit'] = df['Price Per Unit'].astype('float32')
df['Total Spent'] = df['Total Spent'].astype('float32')
df['Location'] = df['Location'].astype('category')

In [73]:
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'], errors='coerce')
df['Payment Method'] = df['Payment Method'].astype('category')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9946 non-null   category
 2   Quantity          9521 non-null   float16
 3   Price Per Unit    9946 non-null   float16
 4   Total Spent       9498 non-null   float16
 5   Payment Method    6822 non-null   category
 6   Location          6039 non-null   category
 7   Transaction Date  9540 non-null   datetime64[us]
dtypes: category(3), datetime64[us](1), float16(3), str(1)
memory usage: 244.4 KB

### Fill the Total Spent with the multi between the Quantity and Price Per Unit

In [78]:
df['Total Spent'] = df['Total Spent'].fillna(
    df['Quantity'] * df['Price Per Unit']
)

In [82]:
df[df['Total Spent'].isna()].head()

c:\Users\mmoed\Downloads\CafeSales-Cleaning\venv\Lib\site-packages\pandas\io\formats\format.py:1466: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
236,TXN_8562645,Salad,NaN,5.0,NaN,NaN,In-store,2023-05-18
278,TXN_3229409,Juice,NaN,3.0,NaN,Cash,Takeaway,2023-04-15
641,TXN_2962976,Juice,NaN,3.0,NaN,NaN,NaN,2023-03-17
738,TXN_8696094,Sandwich,NaN,4.0,NaN,NaN,Takeaway,2023-05-14
1761,TXN_3611851,NaN,4.0,NaN,NaN,Credit Card,NaN,2023-02-09

` We can see that we still have NaN values in Total spent cause we still had some NaNs in the  Qunantity and Price we can handle that later`

In [99]:
df['Quantity'] = df['Quantity'].fillna(
    df['Total Spent'] / df['Price Per Unit']
)

In [100]:
df['Price Per Unit'] = df['Price Per Unit'].fillna(
    df['Total Spent'] / df['Quantity']
)

In [101]:
df['Total Spent'] = df['Total Spent'].fillna(
    df['Quantity'] * df['Price Per Unit']
)

In [102]:
df["Price Per Unit"] = df["Price Per Unit"].fillna(
    df.groupby("Item")["Price Per Unit"]
      .transform(lambda x: x.mode()[0] if not x.mode().empty else np.nan)
)

In [103]:
df["Item"] = df["Item"].astype('category')
df["Price Per Unit"] = df["Price Per Unit"].astype("float32")
df["Item"] = df["Item"].fillna(
    df.groupby("Price Per Unit")["Item"]
      .transform(lambda x: x.mode()[0] if not x.mode().empty else np.nan)
)

In [104]:
df.isna().sum()

Transaction ID         0
Item                   6
Quantity              23
Price Per Unit         6
Total Spent           23
Payment Method      3178
Location            3961
Transaction Date     460
dtype: int64

### Try to fill the remaining NaNs using realtionship between columns

In [109]:
mask = df['Total Spent'].isna() & \
       df['Quantity'].notna() & \
       df['Price Per Unit'].notna()

df.loc[mask, 'Total Spent'] = (
    df.loc[mask, 'Quantity'] * df.loc[mask, 'Price Per Unit']
)

In [110]:
mask = df['Quantity'].isna() & \
       df['Total Spent'].notna() & \
       df['Price Per Unit'].notna()

df.loc[mask, 'Quantity'] = (
    df.loc[mask, 'Total Spent'] / df.loc[mask, 'Price Per Unit']
)

In [111]:
mask = df['Price Per Unit'].isna() & \
       df['Total Spent'].notna() & \
       df['Quantity'].notna()

df.loc[mask, 'Price Per Unit'] = (
    df.loc[mask, 'Total Spent'] / df.loc[mask, 'Quantity']
)

In [112]:
df.isna().sum()

Transaction ID         0
Item                   6
Quantity              23
Price Per Unit         6
Total Spent           23
Payment Method      3178
Location            3961
Transaction Date     460
dtype: int64

`There was no diffrence we will try to find anyother relationship otherwise we will drop them `

In [113]:
print(df['Location'].value_counts())
print(20 * '#')
print(df['Payment Method'].value_counts())

Location
Takeaway    3022
In-store    3017
Name: count, dtype: int64
####################
Payment Method
Digital Wallet    2291
Credit Card       2273
Cash              2258
Name: count, dtype: int64

`We can Note that the distributions are almost blanaced So we can't use the mode method So we will just fill  them with UNKNOWN `

In [115]:
df["Payment Method"] = df["Payment Method"].cat.add_categories("Unknown")
df["Payment Method"] = df["Payment Method"].fillna("Unknown")
df["Location"] = df["Location"].cat.add_categories("Unknown")
df["Location"] = df["Location"].fillna("Unknown")

`Fill the dates using the forward method `

In [120]:
df["Transaction Date"] = df["Transaction Date"].ffill().bfill()

In [121]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9994 non-null   category
 2   Quantity          9977 non-null   float32
 3   Price Per Unit    9994 non-null   float32
 4   Total Spent       9977 non-null   float32
 5   Payment Method    10000 non-null  category
 6   Location          10000 non-null  category
 7   Transaction Date  10000 non-null  datetime64[us]
dtypes: category(3), datetime64[us](1), float32(3), str(1)
memory usage: 303.5 KB

In [122]:
df.isna().sum()

Transaction ID       0
Item                 6
Quantity            23
Price Per Unit       6
Total Spent         23
Payment Method       0
Location             0
Transaction Date     0
dtype: int64

### Note we can drop all the NaN values from our Data Frame

In [127]:
df = df.dropna( subset=['Item', 'Total Spent', 'Quantity', 'Price Per Unit'])

In [128]:
df.isna().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [129]:
df.info()

<class 'pandas.DataFrame'>
Index: 9974 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9974 non-null   str
 1   Item              9974 non-null   category
 2   Quantity          9974 non-null   float32
 3   Price Per Unit    9974 non-null   float32
 4   Total Spent       9974 non-null   float32
 5   Payment Method    9974 non-null   category
 6   Location          9974 non-null   category
 7   Transaction Date  9974 non-null   datetime64[us]
dtypes: category(3), datetime64[us](1), float32(3), str(1)
memory usage: 380.6 KB

### Upload data to an csv File

In [130]:
df.to_csv('clean_cafe_sales.csv', index=False)